# Site settings
baseurl = "https://www.chrisguindon.com"
languageCode = "en-us"
title = "Christopher Guindon - Manager, Web Development at The Eclipse Foundation"
theme = "hugo-cactus-theme"
#themesDir = "node_modules/"
googleAnalytics = "UA-24646327-8"
disqusShortname = "chrisguindon"
enableRobotsTXT = true

[params]
  name = "Christopher Guindon"
  description = "Hello world! I am a highly skilled web developer with over 16 years of experience in all stages of the development cycle for web projects. In addition to my technical expertise, I also have extensive experience managing teams of developers, ensuring that projects are completed on time, within budget, and to the highest quality standards."
  bio = "Manager, Web Development at The Eclipse Foundation"
  twitter = "chrisguindon"
  enableRSS = true

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = ["css/override.css"]
  customJS  = []

  # The variables below are optionally too and can be used to
  # translate or customize each string of the theme.

  # Navigation links
  home = ""
  subscribe = ""
  # Pagination links
  olderPosts = ""
  newerPosts = ""
  readMore = ""
  copyright = "Copyright &copy; 2009-2023 Christopher Guindon. All Rights Reserved."
  # Sharing options and author information in posts
  aboutAuthor = "Manager, Web Development at The Eclipse Foundation"
  tweet = ""
  share = ""
  # 404 page
  title404 = ""
  subtitle404 = ""

  # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
  iconFont = "mono-social"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/chrisguindon"
    facebook = "https://www.facebook.com/christopher.guindon"
    github   = "https://www.github.com/chrisguindon"
    linkedin   = "https://www.linkedin.com/in/chrisguindon/"
